### ISSUE TITLE
Add database

### ISSUE THREAD

**Issue by parpok** [actuallyaridan/chirp#6]
I know this thing uses SQLite but there's no file to use. Having one would help working on some aspects of the app

**Comment by actuallyaridan** [comment]
There is a lot of sensitive information in the database, including hashed passwords. 
I might create an empty one in the future though.

**Comment by parpok** [comment]
i mean even a sample db with like user: Test: password: Test 
something to just test changes locally

**Comment by ghost** [comment]
> There is a lot of sensitive information in the database, including hashed passwords. I might create an empty one in the future though.

Yeah I would be able to contribute to the project if I just had a Sample Database

**Comment by Pinball3D** [comment]
@parpok @TheHCJ if you check #13 I added an example database.

**Comment by ghost** [comment]
> @parpok @TheHCJ if you check #13 I added an example database.

Thank you so much! Your a lifesaver!
